### ISSUE TITLE
Skip validation

### ISSUE THREAD

**Issue by dariooddenino** [thomashoneyman/purescript-halogen-formless#20]
It would be useful to be able to skip the validation and not having to write a record of `H.hoistFn_ identity`.

I guess the best approach whould be to change validators to a `Maybe`, but for now I'm using this approach with `heterogeneous`:

```
data EmptyValidators = EmptyValidators

instance emptyValidators ::
  (Monad m) =>
  Mapping EmptyValidators a (F.Validation form m e i i) where
  mapping EmptyValidators = const (F.hoistFn_ identity)

noValidation
  :: forall form fields m vs xs
   . Monad m
  => RL.RowToList fields xs
  => Newtype (form Record (F.Validation form m)) { | vs }
  => Newtype (form Record F.InputField) { | fields }
  => MapRecordWithIndex xs (ConstMapping EmptyValidators) fields vs
  => form Record F.InputField
  -> form Record (F.Validation form m)
noValidation = wrap <<< hmap EmptyValidators <<< unwrap
```

and then
```
validators :: Form Record (F.Validation Form Aff)
validators = noValidation inputs
```

**Comment by thomashoneyman** [comment]
Another possibility is to make the entire field optional (`Maybe (form Record F.Validation form m)`), and in that way skip all sorts of error-checking and transformation computations within the library in favor of simply tracking and updating form state and returning the inputs as validated results in a submission message.

This function is a reasonable approach for any users of `v0.2.0`, but I'd like to explore what it would look like to only optionally require the `validators` field.
