### ISSUE TITLE
Small bug in basic example

### ISSUE THREAD

**Issue by rinn7e** [thomashoneyman/purescript-halogen-formless#24]
The basic example seems to miss binding the handling function for formless.
 
Current code:
https://github.com/thomashoneyman/purescript-halogen-formless/blob/v0.2.0/example/basic/Component.purs#L43-L49
```
HH.slot unit F.component
    { inputs
    , validators
    , submitter: pure <<< F.unwrapOutputFields
    , render: renderFormless
    }
    (const Nothing)
```

Fix:
```
HH.slot unit F.component
    { inputs
    , validators
    , submitter: pure <<< F.unwrapOutputFields
    , render: renderFormless
    }
    (HE.input HandleFormless)

**Comment by thomashoneyman** [comment]
Thanks for pointing this out! I've fixed and pushed to master in 38bdb58.
