### ISSUE TITLE
Send requests to external components

### ISSUE THREAD

**Issue by dariooddenino** [thomashoneyman/purescript-halogen-formless#28]
If I'm not mistaken, right now it's not possible to send requests to external components.

I can send actions with:
`H.query slot $ H.action $ F.send slot' (H.action myAction)`

But I can't do the equivalent of:
`H.query slot $ H.request myRequest`

**Comment by thomashoneyman** [comment]
@dariooddenino That's right, in the current version I haven't supported doing this. In the `halogen-v5` branch I _have_ supported it, as I was expecting for Halogen 5 to come out a bit sooner than it has. 

Given that I probably ought to have support for this in v4 regardless and it's unclear when v5 will arrive, this should be fixed!
