### ISSUE TITLE
Update for Halogen 5

### ISSUE THREAD

**Issue by thomashoneyman** [thomashoneyman/purescript-halogen-formless#45]
Formless is not compatible with the [release candidate for Halogen 5](https://github.com/slamdata/purescript-halogen/releases/tag/v5.0.0-rc.3) and will prevent users and libraries that depend on Formless from upgrading when Halogen is released.

**Comment by linearray** [comment]
Looks great! Is there anything missing for halogen 5 support?

**Comment by thomashoneyman** [comment]
Nothing is missing — #46 closes this issue; I haven’t merged it because Halogen hasn’t had an official release yet, but since plenty of people are on the release candidate perhaps I should, and just tag it when Halogen 5 does have its official release.

In the meantime you can point at that branch and use this with Halogen 5 just fine. Halogen RealWorld does so.
