### ISSUE TITLE
Add a component template file/directory?

### ISSUE THREAD

**Issue by JordanMartinez** [thomashoneyman/purescript-halogen-formless#49]
Similar to what I did with [`ComponentTemplate.purs`](https://github.com/JordanMartinez/learn-halogen/blob/latestRelease/src/05-ComponentTemplate-A.purs), would you be up for me adding something like that here? Or should I perhaps store that in my learning repo?

Due to how much stuff goes on in creating a form, I think this should be a directory with these files:
- data and validation: defines a single type in the form, its instances, and its validation code
- component - commented: a Formless component template file that explains everything (useful for new learners)
- component - uncommented: a Formless component template file that explains nothing and is used to create the boilerplate to make the thing work (useful for developers)

**Comment by thomashoneyman** [comment]
I'm sorry I took so long to get back to this. I think this is a good idea and a welcome addition to the library. I didn't want to jump the gun on adding the template until I felt things were more stable with all the Halogen 5 upgrades, but at this point it doesn't feel like much more will change.

I'd understand if you no longer had this top of mind and weren't able to contribute it, but if you do still want to, I'd be happy to merge it in.

**Comment by JordanMartinez** [comment]
> I didn't want to jump the gun on adding the template until I felt things were more stable with all the Halogen 5 upgrades, but at this point it doesn't feel like much more will change.

Makes sense.

I'd still like to contribute it. There were a few things I didn't understand when I wrote it, so this would be helpful for me in that way, too.

**Comment by thomashoneyman** [comment]
Closed in #53
