### ISSUE TITLE
README example has invalid syntax

### ISSUE THREAD

**Issue by liam-cb** [thomashoneyman/purescript-halogen-formless#57]
## Environment

* `purescript-halogen` v5.0.0-rc.7
* `purescript-halogen-formless` v1.0.0-rc.1

## Current behavior

The example in the README uses a pun on a record update

```
spec :: forall m. Monad m => F.Spec' DogForm Dog m
spec = F.defaultSpec { render, handleEvent = F.raiseResult }
```

this isn't valid to avoid syntactic ambiguities with the update syntax

## Expected behavior
Probably just this:

```
spec :: forall m. Monad m => F.Spec' DogForm Dog m
spec = F.defaultSpec { render = render, handleEvent = F.raiseResult }
```

**Comment by thomashoneyman** [comment]
Thanks, @liam-cb -- you're right, the second example is the correct one.

**Comment by thomashoneyman** [comment]
Fixed in https://github.com/thomashoneyman/purescript-halogen-formless/commit/4542d08de1edb744e0c8a540766ec0a44af8ee60
