### ISSUE TITLE
Documentation on Pursuit?

### ISSUE THREAD

**Issue by goertzenator** [thomashoneyman/purescript-halogen-formless#74]
Can the docs for this package be published on https://pursuit.purescript.org ?

**Comment by thomashoneyman** [comment]
Hi @goertzenator! Sorry about that; these were originally not uploaded due to an issue where Halogen could not be uploaded, but that's been resolved for a long time and I simply forgot. Here you go:

https://pursuit.purescript.org/packages/purescript-halogen-formless

**Comment by goertzenator** [comment]
A nudge to push updated docs to pursuit. ;)

**Comment by thomashoneyman** [comment]
Sorry about that! Done :)
