### ISSUE TITLE
Update example components to use `submitPreventDefault`

### ISSUE THREAD

**Issue by chiroptical** [thomashoneyman/purescript-halogen-formless#81]
In #80, @gillchristian and I added the ability to use a more idiomatic form and prevent the default event when using `onSubmit`. It would be awesome to update the examples/readme to match the more idiomatic style in the readme example.

**Comment by thomashoneyman** [comment]
Formless 3 now provides you with a `handleSubmit` function that can be used to handle submission events on your form (including calling `preventDefault` for you), and a separate `submit` function that can be used to imperatively submit the form without access to an event.

See the basic example:
https://github.com/thomashoneyman/purescript-halogen-formless/blob/60546a731637aca21b943288b73ecf6382c6b5d3/example/Example/Basic.purs#L62
