### ISSUE TITLE
Problem getting the code from current README.md to compile

### ISSUE THREAD

**Issue by farzadbekran** [thomashoneyman/purescript-halogen-formless#83]
Hi!
I put the code from the readme into a file and tried to compile it, but I'm getting a type error with type signatures for the `handleAction` and `handleQuery` functions. I've put the code [here](https://gist.github.com/farzadbekran/e51f37a49cee00ce3d65545c9a5a9ae2) if you want to test it.

They work if I change the signatures to `H.HalogenM _ _ _ _ _ Unit` and `H.HalogenM _ _ _ _ _ (Maybe a)`, but it would be nice to actually see the types.

**Comment by thomashoneyman** [comment]
I’m responding from mobile so please forgive the formatting :)

The problem that I see right away is that the FormOutput type in Formless is supposed to take a row type, but in the README I mistakenly provide a record (Output). It should be:

    F.FormOutput (Form F.FieldOutput)

instead of

    F.FormOutput { | Form F.FieldOutput }
    
(which is the type that Output is a synonym for).

**Comment by farzadbekran** [comment]
Thanks for the response. Changing it to `F.FormOutput (Form F.FieldOutput)` gives me this error:
```
 Could not match kind
                
    Type -> Type
                
  with kind
        
    Type
```
Note: `F.FormOutput` is defined like this:
``` purescript
data FormOutput :: Row Type -> Type -> Type
data FormOutput fields output
  = Raise output
  | Eval (FormlessAction fields)
```

**Comment by thomashoneyman** [comment]
🤦‍♀️ Right, it should be `(F.FormOutput (Form F.FieldState) Output)` then. Though I usually just throw a `_` in there for convenience. In general, these type variables in Formless map to each other:

```
inputs -> MyForm F.FieldInput
fields -> MyForm F.FieldState
validators -> MyForm F.FieldValidation
results -> MyForm F.FieldResult
outputs -> MyForm F.FieldOutput
```

**Comment by farzadbekran** [comment]
Got it, thanks again!
