### ISSUE TITLE
Project doesn't build

### ISSUE THREAD

**Issue by dnikolovv** [thomashoneyman/purescript-halogen-formless#86]
It depends on the `map-variant` branch from https://github.com/MonoidMusician/purescript-variant which has changed a few hours ago with `1aba110a6f3fad07355f1730b4755716a3855352`.

Perhaps it should use a specific commit as version?

**Comment by thomashoneyman** [comment]
Sorry about that! It’s somewhat good news, though, as once that PR merges I can actually release Formless 3 properly. In the meantime we can fix this library and point to a specific commit.

**Comment by dnikolovv** [comment]
I've submitted a PR pinning it to the latest commit before the breaking changes.
